GitbookIO/markup-it

package.json
syntaxes/markdown/__tests__/specs.js
syntaxes/markdown/__tests__/specs/image.html
syntaxes/markdown/__tests__/specs/image.md
syntaxes/markdown/inline.js

This PR adds support for image titles in markdown sources. Till now, only alt text and src of image has been processed and title has been ignored. Following (standard) format is now supported:
```md
```
It also fixes MdIdempotence check, which caused successful tests even for incorrect conditions.

Support for image title in markdown

---

lib/models/rules.js
lib/slate/encode.js

This PR contain two commits regarding the ability to dynamically add custom rules to existing syntaxes.
* Prioritize added rules
New, User-created rules added to an existing syntax (such as the MarkDown syntax) should be processed before the pre-existing rules. (Otherwise pre-existing rules with broad matching patterns will always be used instead of the custom rule added in userland).
* Let the user specify custom marks and void nodes with Slate utils `encode`

Small Improvements to custom rules support

---

package.json
test/from-html/links/only/output.yaml
test/from-html/links/prefixed/output.yaml
test/from-markdown/links/def/output.yaml
test/from-markdown/links/normal/output.yaml
test/from-markdown/links/url-email/output.yaml
test/from-markdown/links/url-in-link/output.yaml
test/from-markdown/links/url/output.yaml
yarn.lock

This PR fixes unit tests to update slate to `0.16.8` (dev dependency).

Update slate to 0.16.8

---

package.json
src/markdown/blocks/code.js
test/from-markdown/code-blocks/no-syntax-start-indent/input.md
test/from-markdown/code-blocks/no-syntax-start-indent/output.yaml
test/from-markdown/lists/ul-loose/input.md
test/from-markdown/lists/ul-loose/output.yaml
yarn.lock

From markdown:
```js
indented first line
etc.
```
was losing the starting indentation:
```js
indented first line
etc.
```

Fix parsing starting indent of code fences

---

src/markdown/inlines/html.js
test/from-markdown/html/p-not-merged/input.md
test/from-markdown/html/p-not-merged/output.yaml
test/from-markdown/html/p/input.md
test/from-markdown/html/p/output.yaml
test/to-markdown/html/p/input.yaml
test/to-markdown/html/p/output.md

Serialization of nodes with `INLINES.HTML` as failing in markdown.
This PR fixes it (Fix #55) and also merge consecutive HTML nodes into one (much better if we want to support edition in the editor).

Fix #55: markdown with html serialization

---

src/markdown/re/inline.js
src/markdown/utils.js
test/from-markdown/images/url-with-title-and-whitespace/input.md
test/from-markdown/images/url-with-title-and-whitespace/output.yaml
test/from-markdown/images/url-with-whitespace/input.md
test/from-markdown/images/url-with-whitespace/output.yaml
test/from-markdown/links/url-with-whitespace-escaped/input.md
test/from-markdown/links/url-with-whitespace-escaped/output.yaml
test/from-markdown/links/url-with-whitespace-with-title/input.md
test/from-markdown/links/url-with-whitespace-with-title/output.yaml
test/from-markdown/links/url-with-whitespace/input.md

This PR adds back whitespaces in urls, but it escapes whitespaces during serialization.

Fix whitespaces in urls (links and images)

---

src/markdown/re/block.js
test/from-markdown/code-blocks/empty/input.md
test/from-markdown/code-blocks/empty/output.yaml

This PR fixes parsing of empty code blocks.
It updates the regex using the latest in [marked](https://github.com/chjj/marked/blob/master/lib/marked.js#L78) (since markupit is based on kramed, which is based on marked)

Fix empty code block

---

src/markdown/utils.js
test/all.js
test/from-markdown/links/url-with-encoded-parenthesis/output.yaml
test/from-markdown/links/url-with-malformed-encoding/input.md
test/from-markdown/links/url-with-malformed-encoding/output.yaml

There was an issue with the content 
```
{% youtube %}https://www.youtube.com/watch?v=1Uv1Kmvhtc4{% endyoutube %}
```
that would try to parse the following link `https://www.youtube.com/watch?v=1Uv1Kmvhtc4{%` and fail at decoding URI.
This avoid this failure, and adds detection of incomplete test folders.
I'll look into the templating parsing issue as well in another PR.

Fix URI decoding

---

src/html/deserializeHtml.js
test/from-html/dirty-nbsp/input.html
test/from-html/dirty-nbsp/output.yaml
test/from-html/real-world-list/output.yaml
test/from-html/real-world-rich/output.yaml

Unexpected non-breaking spaces in a document can cause lots of quirks and issues.
People never really expect or desire docs to contain non-breaking spaces, but browsers create them when copy/pasting HTML
This PR replaces all non-breaking spaces with regular spaces when parsing HTML

Fix: sanitize non-breaking spaces

---

src/html/parse.js
test/from-html/line-breaks/input.html
test/from-html/line-breaks/output.yaml

This is an obvious typo, and I don't think adding a test for it is strictly necessary; it's just here to show that the typo does trigger a bug.

Issue #76 /n is not a valid line break

---

src/markdown/blocks/index.js
test/from-markdown/hr/with-spaces/input.md
test/from-markdown/hr/with-spaces/output.yaml

Otherwise, HRs are considered as lists in case they include spaces.
Example:
```md
Hello
- - -
World
```
becomes:
```
Hello
-
-
World
```

Parse hr before lists

---

src/markdown/utils.js
test/to-markdown/images/escape-url-whitespace/output.md
test/to-markdown/links/escape-href-whitespace/output.md

GitHub doesn’t support whitespaces in markdown links. ([example gist](https://gist.github.com/SamyPesse/7fb520dabae059ff68ae1c4fa8551b3c)).
This PR fixes it.

Fix whitespace escaping in markdown links

---

src/markdown/blocks/index.js
test/from-markdown/links/reference-with-html/input.md
test/from-markdown/links/reference-with-html/output.yaml

Fix #97 
Reference definitions at the end of the document were not parsed yet when we encountered the first links

Fix link reference parsing after HTML

---

package.json
src/asciidoc/inlines/escape.js
src/html/escape.js
src/html/unescape.js
src/markdown/utils.js
test/from-html/entities/input.html
test/from-html/entities/output.yaml
test/from-markdown/html/entities-char/input.md
test/from-markdown/html/entities-char/output.yaml
test/to-markdown/text-escaping/emojis/input.yaml
test/to-markdown/text-escaping/emojis/output.md
yarn.lock

This PR fixes the decoding of emojis and other HTML entities when parsing HTML or Markdown.
It uses [`entities`](https://yarnpkg.com/en/package/entities) instead of [`html-entities`](https://yarnpkg.com/en/package/html-entities) because it doesn't support emojis: https://github.com/mdevils/node-html-entities/pull/18

Fix decoding of HTML entities (emojis)

---

test/from-markdown/html/comment-multi-lines/input.md
test/from-markdown/html/comment-multi-lines/output.yaml

This PR adds a test (that passed) for multi-lines HTML comments in Markdown.
It follows a support ticket on GitBook.

Add test for multi-lines HTML comments

---

src/markdown/inlines/bold.js
src/markdown/inlines/code.js
src/markdown/inlines/italic.js
src/markdown/inlines/strikethrough.js
src/markdown/utils.js
test/to-markdown/marks/bold-whitespace/input.yaml
test/to-markdown/marks/bold-whitespace/output.md
test/to-markdown/marks/code-whitespace/input.yaml
test/to-markdown/marks/code-whitespace/output.md
test/to-markdown/marks/italic-whitespace/input.yaml
test/to-markdown/marks/italic-whitespace/output.md
test/to-markdown/marks/strikethrough-whitespace/input.yaml
test/to-markdown/marks/strikethrough-whitespace/output.md

The following Slate document:
```
Some <bold>text </bold>content.
```
is currently serialized as:
```
Some **text **content.
```
Which is not valid markdown (doesn't work on GitHub for example). It should be:
```
Some **text** content.
```
We need to keep mind that it may start/end with 1+ white space, or a line break, etc.

Fix marks serialization when starting/ending with a space

---

src/markdown/liquid/escape.js
test/from-markdown/custom-blocks/data-html/input.md
test/from-markdown/custom-blocks/data-html/output.yaml
test/to-markdown/custom-blocks/data-html/input.yaml
test/to-markdown/custom-blocks/data-html/output.md

This bug has been reported in GitBook. Embeds have JSON in their data property so we end up with something like:
```
<embed data={{ html: '<div style="background-color: red;" />' }} />
```
It's serialized to:
```
{% embed data="{ \"html\": \"<div style=\\"background-color: red;\\" />\" }" %}
```
Which leads to an invalid JSON string, the expected result is:
```
{% embed data="{ \"html\": \"<div style=\\\"background-color: red;\\\" />\" }" %}
```

Fix slashes escaping in data properties

---

package.json
src/models/serializer.js
yarn.lock

We no longer use `text.characters` which is deprecated. This is a non breaking change.
After merging this, we will need to publish markup-it as an actual release.

Upgrade to Slate 0.34.3

---

src/html/inlines/code.js
src/html/inlines/escape.js
src/html/inlines/index.js
test/from-html/text/unescaping/input.html
test/from-html/text/unescaping/output.js
test/from-markdown/text-escaping/html/input.md
test/from-markdown/text-escaping/html/output.js
test/to-html/text-escaping/input.js
test/to-html/text-escaping/output.html
test/to-markdown/table/multi-paragraph-html-escaping/input.js
test/to-markdown/table/multi-paragraph-html-escaping/output.md
test/to-markdown/text-escaping/html/input.js
test/to-markdown/text-escaping/html/output.md

A user reported an issue with Markdown serialization where HTML characters were not escaped. For example, `<C>` would be serialized to `<C>` instead of `&lt;C&gt;`.
See https://github.com/GitbookIO/markup-it/compare/fix/escape-html?expand=1#diff-796e4f3910aef133cdb762f2de0f9629 for the test case.

Escape HTML from all text nodes

---

package.json
src/markdown/utils.js
test/from-markdown/images/markdown-like-url/input.md
test/from-markdown/images/markdown-like-url/output.js
test/from-markdown/images/with-alt-absolute/input.md
test/from-markdown/images/with-alt-absolute/output.js
test/to-markdown/images/markdown-like-url/input.js
test/to-markdown/images/markdown-like-url/output.md
test/to-markdown/images/with-alt-absolute/input.js
test/to-markdown/images/with-alt-absolute/output.md
yarn.lock

Absolute URLs represent static resources instead of file paths, so they should never be unescaped.

Markdown: Prevent unescaping absolute URLs at deserialization

---

src/markdown/blocks/heading.js
test/from-markdown/headings/link/input.md
test/from-markdown/headings/link/output.js

Trimming the text on first/last node in this case might fail.
We prevent trimming the first/last node of the heading if this is not a text.

Fix parsing headings including blocks

---

package.json
yarn.lock

`indent-string@4.0.0` uses object rest spread

Revert indent-string@^3.2.0 to be compatible with Edge

---

__tests__/__fixtures__/from-markdown/frontmatter/invalid/input.md
__tests__/__fixtures__/from-markdown/frontmatter/invalid/output.js
__tests__/__fixtures__/from-markdown/frontmatter/looks-like-front-matter-2/input.md
__tests__/__fixtures__/from-markdown/frontmatter/looks-like-front-matter-2/output.js
__tests__/__fixtures__/from-markdown/frontmatter/looks-like-front-matter-3/input.md
__tests__/__fixtures__/from-markdown/frontmatter/looks-like-front-matter-3/output.js
__tests__/__fixtures__/from-markdown/frontmatter/looks-like-front-matter/input.md
__tests__/__fixtures__/from-markdown/frontmatter/looks-like-front-matter/output.js
__tests__/__fixtures__/from-markdown/frontmatter/only-string/input.md
__tests__/__fixtures__/from-markdown/frontmatter/only-string/output.js
package.json
src/markdown/document.js
yarn.lock

_Better alternative to #150 (`gray-matter` incorrectly detects content as front matter when there is no delimiter)._
Currently, invalid front matter makes the deserialization using the MarkdownParser fail, either with a `YAMLException` (error from front-matter) or a `Expected [K, V] tuple: T` error (when passing a string instead of an object to Immutable.fromJS()).
This PR handles these errors gracefully. In case of error or if the text front matter is a simple string, we parse the whole text as pure markdown.

Gracefully parse front matter

---

__tests__/__fixtures__/to-markdown/table/html-table-and-paragraph/input.js
__tests__/__fixtures__/to-markdown/table/html-table-and-paragraph/output.md
src/markdown/blocks/table.js

When exporting a complex `table` to markdown, it is written as HTML to preserve formatting.
However, `markup-it` currently doesn't append newline characters `\n\n` after the HTML table in the markdown output.
This leads to invalid markdown when the table is not the last element of content, for instance:
```html
<table aligns={[null, null]}>
...
</table>
<paragraph>Some text</paragraph>
```
leads to
```md
<table>
...
</table>Some text
```
instead of
```md
<table>
...
</table>
Some text
```
This PR fixes this issue by properly appending newline characters after the HTML table in markdown.

Ensure HTML tables in markdown are properly followed by newlines
